Feature/HPO create account test case
MNadolsky/ThePlatform pull request #15
Opened 2020-11-20 02:45 UTC by agrant23

2020-11-24 09:06 UTC, MNadolsky requested changes

2020-11-24 09:06 UTC, MNadolsky commented on .gitignore
> +sand_box_tools.py
something like sand_box*.py

2020-11-24 09:06 UTC, MNadolsky commented on coinbase_HPO_createAccount_tests.py
> +
move this to coinbase_tests.py

2020-11-24 09:06 UTC, MNadolsky commented on config.py
> +import os
remove

2020-11-24 09:06 UTC, MNadolsky commented on pages/coinbase/homepage.py
> +    account_dial_box_loc =       (by.XPATH, "//span[.='Create account']")
inconsistent indentation.

don't use the word "dial;" use the full word. There is no memory limit, so just use full variable names _especially_ when you only use them once or twice. Only consider shortening them when they're used frequently. For a reader, it's not worth the cognitive effort of parsing shortened variable names when it's only used once.

2020-11-24 09:06 UTC, MNadolsky commented on pages/coinbase/homepage.py
> +        self.account_dial_box =        Element(
inconsistent indention. 

don't abbreviate words in variable names.

2020-11-30 05:04 UTC, MNadolsky requested changes

2020-11-30 05:04 UTC, MNadolsky commented on coinbase_tests.py
> +class HomePageSetup(unittest.TestCase):
use "template" in template class names to distinguish from class names.

2020-11-30 05:04 UTC, MNadolsky commented on coinbase_tests.py
> +        self.driver = webdriver.Chrome(root_path + config.win_chromedriver_path)
incompatible with mac

2020-11-30 05:04 UTC, MNadolsky commented on pages/coinbase/homepage.py
> +        self.total_product_link_list = [
scrub all unused code from the branch

2020-12-02 01:21 UTC, agrant23 commented on coinbase_tests.py
> +        self.driver = webdriver.Chrome(root_path + config.win_chromedriver_path)
If you check this PR first check my comment in the PR for feature/HPOsafeSecure

2020-12-08 20:31 UTC, MNadolsky approved these changes

2020-12-23 02:10 UTC, merged