Feature/hp osafe secure links
MNadolsky/ThePlatform pull request #17
Opened 2020-11-29 23:39 UTC by agrant23

2020-11-29 23:40 UTC, agrant23 commented on coinbase_tests.py
I debated using driver.back() or creating three more test methods. Let me know which is better.

2020-11-30 05:02 UTC, MNadolsky requested changes

2020-11-30 05:02 UTC, MNadolsky commented on coinbase_tests.py
This is fine, except that page already has driver. `page.driver.back()`

2020-11-30 05:02 UTC, MNadolsky commented on coinbase_tests.py
> +        driver = self.driver
remove this; page has driver

2020-11-30 05:02 UTC, MNadolsky commented on pages/coinbase/homepage.py
> +            time.sleep(.5)
why did you add this? `send_keys()` should do the trick. If you use `time.sleep()` you may as well use `element.click()`

2020-11-30 05:02 UTC, MNadolsky commented on pages/coinbase/homepage.py
> +        self.total_product_link_list = [
Why did you add this? You don't use it.

2020-11-30 05:02 UTC, MNadolsky commented on pages/coinbase/homepage.py
> +    create_account_dial_box_loc = (by.XPATH, "//span[.='Create account']")
I don't think you use this either. Please scrub this branch of this sort of thing.

2020-11-30 05:02 UTC, MNadolsky commented on coinbase_tests.py
> +    -Clicking on the Customer fund are secure link navigates the user to the
state what the corresponding urls are.

EDIT: I changed my mind; this is a little nitpicky. You don't have to, and it might be better not to. Up to you.

2020-11-30 05:02 UTC, MNadolsky commented on coinbase_tests.py
> +class HomePageSetup(unittest.TestCase):
Put the word "template" in this class name so we know it's a template and not a test case.

2020-11-30 05:02 UTC, MNadolsky commented on coinbase_tests.py
> +        self.driver = webdriver.Chrome(root_path + config.win_chromedriver_path)
This is incorrect. what if someone on a mac tries to run this?

Project has 

```
root_path = os.path.dirname(os.path.realpath(__file__))
if 'Darwin' in platform.system():
    chromedriver_path = config.mac_chromedriver_path
else: 
    chromedriver_path = config.win_chromedriver_path
```

so that `chromedriver_path` will always return the correct path

2020-12-02 01:04 UTC, agrant23 commented on coinbase_tests.py
> +        self.driver = webdriver.Chrome(root_path + config.win_chromedriver_path)
I'm using the same block of code you pasted here in this setUp. Or root_path and chromedriver path are class variables that are being used in that block of code and within my setUp method within HomePageSetup class. I did change that class name

2020-12-02 01:11 UTC, agrant23 commented on pages/coinbase/homepage.py
I didn't scrub everything in homepage.py,  but I did take out all of the unnecessary attributes. Let me know if you want me to scrub these small edits.

2020-12-08 20:31 UTC, MNadolsky approved these changes

2020-12-23 01:38 UTC, merged